# TEST EXECUTION CONFIGURATION

# Browser
browser=chrome

# Selenium Server: this could be local or depending on
seleniumServer=http://127.0.0.1:4444/wd/hub


# Timeout is used to define implicit wait time i.e. global wait time in seconds for page elements
timeout=30

# Execution environment
env=local

#Application Login Info
URL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
userPassword=admin123
slackWorkspace=https://neurosensumworkspace.slack.com/sign_in_with_password
slackUser=manisha.panchal@neurosensum.com
slackPassword=M@ni20252025









